version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_logs:/var/log/nginx  # Volume partagé pour les logs NGINX
    ports:
      - "80:80"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Configuration Logstash
      - ./nginx_logs:/var/log/nginx  # Volume partagé pour accéder aux logs NGINX
    ports:
      - "1025:1025/udp"  # Port pour recevoir les logs UDP
      - "5000:5000"      # Port pour recevoir les logs Beats
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
  nginx_logs:  # Volume pour partager les logs NGINX

networks:
  elk:
    driver: bridge
